In [1]:
import torch

In [2]:
import torchvision

In [3]:
# It is false because there is no GPU as we are using CPU
print (torch.cuda.is_available())


False


# Torch Tensors

In [4]:
# This is a 1-D Tensor
a = torch.tensor([2,3,1])
print (a)

tensor([2, 3, 1])


In [7]:
b = torch.tensor([[2,3,1],[2,3,1],[2,3,1]])
print (b)

tensor([[2, 3, 1],
        [2, 3, 1],
        [2, 3, 1]])


In [8]:
# The size of the tensors
print (a.shape)
print (b.shape)
print (a.size())
print (a.size())

torch.Size([3])
torch.Size([3, 3])
torch.Size([3])
torch.Size([3])


In [9]:
# Get the number of rows of b
print (b.shape[0])

3


In [11]:
# Get the float tensor
c = torch.FloatTensor([[2,3,1],[2,3,1],[2,3,1]])
print (c)

tensor([[2., 3., 1.],
        [2., 3., 1.],
        [2., 3., 1.]])


In [13]:
# Get the double tensor
d = torch.DoubleTensor([[2,3,1],[2,3,1],[2,3,1]])
print (d)
print (d.dtype)

tensor([[2., 3., 1.],
        [2., 3., 1.],
        [2., 3., 1.]], dtype=torch.float64)
torch.float64


In [14]:
print (c.mean())

tensor(2.)


In [15]:
print (c.std())

tensor(0.8660)


In [22]:
# Reshape b
# Note: if one o fthe dimensions is -1, its size can be inferre d
print (b.view(-1,1))
print (b.view(9))
print (b.view(-1,3))
print (b.view(3,3))

# Assign b a new shape
b = b.view(-1,1)
print (b)
print (b.shape)

#We can even reshape 3D tensors
print ('\n')

#Create a 3D Tensor with 2 channels, 3 row and 4 columns (channels,rows, columns)
three_dim = torch.randn(2,3,4)

print ('\n')
print(three_dim.view(2,12)) #Reshape to 2 rows, 12 columns
print ('\n')
print(three_dim.view(2,-1))


tensor([[2],
        [3],
        [1],
        [2],
        [3],
        [1],
        [2],
        [3],
        [1]])
tensor([2, 3, 1, 2, 3, 1, 2, 3, 1])
tensor([[2, 3, 1],
        [2, 3, 1],
        [2, 3, 1]])
tensor([[2, 3, 1],
        [2, 3, 1],
        [2, 3, 1]])
tensor([[2],
        [3],
        [1],
        [2],
        [3],
        [1],
        [2],
        [3],
        [1]])
torch.Size([9, 1])




tensor([[-0.7145, -0.6491,  1.6036,  1.5066, -0.8156, -1.0339, -2.5288, -0.5609,
          0.4193,  1.0490,  0.6291,  1.3749],
        [ 1.0916, -2.0921,  0.2560,  0.3726,  1.7806, -0.9531,  0.0686,  1.4651,
          0.7138, -0.0122, -0.3405, -1.4754]])


tensor([[-0.7145, -0.6491,  1.6036,  1.5066, -0.8156, -1.0339, -2.5288, -0.5609,
          0.4193,  1.0490,  0.6291,  1.3749],
        [ 1.0916, -2.0921,  0.2560,  0.3726,  1.7806, -0.9531,  0.0686,  1.4651,
          0.7138, -0.0122, -0.3405, -1.4754]])


In [23]:
# Create a matrix with random numbers between 0 and 1.
r = torch.rand(4,4)
print (r)

tensor([[0.6918, 0.7657, 0.7296, 0.2095],
        [0.3749, 0.6463, 0.8426, 0.4882],
        [0.3074, 0.9316, 0.1596, 0.2673],
        [0.0700, 0.1975, 0.9031, 0.0037]])


In [24]:
#Create a matrix with random numbers taken from a normal distribution with mean 0 and variance 1
r2 = torch.randn(4,4)
print (r2)
print (r2.dtype)

tensor([[ 0.5418,  0.2757,  0.3207, -0.8429],
        [-1.5594,  0.5978, -0.4721,  0.0557],
        [-1.4402,  0.0494,  0.6751,  0.3709],
        [-0.5511, -1.6274,  1.3308, -1.4401]])
torch.float32


In [25]:
# Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6, 10, (5,))
print (in_array)
print (in_array.dtype)

tensor([6, 6, 6, 6, 8])
torch.int64


In [26]:
# Create a 2-D array (or matrix) of size 3x3 filled with random integers from values between 6 and 9 (exclusive of 10)
in_array2 = torch.randint(6, 10, (3,3))
print (in_array2)

tensor([[9, 9, 9],
        [9, 7, 7],
        [6, 8, 6]])


In [27]:
#Get the number of elements in in_array
print (torch.numel(in_array))

#Get the number of elements in in_array2
print (torch.numel(in_array2))



5
9


In [28]:
#Construct a 3x3 matrix of zeros and of dtype long:
z = torch.zeros(3, 3, dtype=torch.long)
print(z)

#Construct a 3x3 matrix of ones

o = torch.ones(3,3)
print (o)
print (o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [29]:
r2_like = torch.randn_like(r2, dtype=torch.double) #convert the data type of the tensor
print (r2_like)

tensor([[-0.3445,  0.4236,  1.4530,  0.0037],
        [-1.0386, -0.8374, -2.0150,  1.1276],
        [ 0.6289,  1.1490, -1.2858, -0.4734],
        [-1.2531,  0.9861,  0.2464,  0.3150]], dtype=torch.float64)


In [30]:
# Add two tensors, make sure they ar ethe same size and data type
add_result = torch.add(r,r2)
print (add_result)

tensor([[ 1.2336,  1.0414,  1.0504, -0.6334],
        [-1.1845,  1.2441,  0.3705,  0.5439],
        [-1.1328,  0.9810,  0.8347,  0.6383],
        [-0.4811, -1.4299,  2.2340, -1.4364]])


In [31]:
#In-place addition (change the value of r2)
r2.add(r)  #r2 = torch.add(r,r2)
print(r2)

tensor([[ 0.5418,  0.2757,  0.3207, -0.8429],
        [-1.5594,  0.5978, -0.4721,  0.0557],
        [-1.4402,  0.0494,  0.6751,  0.3709],
        [-0.5511, -1.6274,  1.3308, -1.4401]])


In [32]:
print (r2[:,1])
print (r2[:,:2])
print (r2[:3,:])
num_ten = r2[2,3]
print (num_ten)
print (num_ten.item())
print (r2[2,:])

tensor([ 0.2757,  0.5978,  0.0494, -1.6274])
tensor([[ 0.5418,  0.2757],
        [-1.5594,  0.5978],
        [-1.4402,  0.0494],
        [-0.5511, -1.6274]])
tensor([[ 0.5418,  0.2757,  0.3207, -0.8429],
        [-1.5594,  0.5978, -0.4721,  0.0557],
        [-1.4402,  0.0494,  0.6751,  0.3709]])
tensor(0.3709)
0.3709176480770111
tensor([-1.4402,  0.0494,  0.6751,  0.3709])
